{{- if hasKey .Values "migrations" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,succeeded
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: {{ .Values.migrations.timeout | default 60 }}
  activeDeadlineSeconds: {{ .Values.migrations.timeout | default 60}}
  template:
    spec: 
      restartPolicy: Never
      {{- with .Values.deployment.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount }}
      serviceAccountName: {{ .Values.namespace }}
      {{- end }}
      containers:
        - name: migrations
          image: {{ .Values.deployment.image.repository }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        {{- if hasKey .Values.deployment "env" }}
          env:
        {{- with .Values.deployment.env }}
            {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
          command:
            - {{ .Values.migrations.command | default "exit" }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
{{- end }}